### ISSUE TITLE
UI Failing to load due to null pointer exception

### ISSUE THREAD

**Issue by bcherrington** [oslabs-beta/port-navigator#101]
The value of IPAM.Confg object can be null in some cases, causing the code to retrieve the Gateway and Subnet mask to throw an exception. A check for null should be added to prevent this and return null in the conditional ternary operator.

**Comment by bcherrington** [comment]
Pull request has been submitted to fix this issue.

**Comment by ClStewart1212** [comment]
Thanks for your contribution bcherrington! The PR has been merged. Closing your issue.
